Update CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,5 +19,8 @@ jobs:
         with:
           go-version: "1.25.1"
 
-      - name: Force Failure
-        run: (exit 1)
+      # - name: Force Failure
+      #   run: (exit 1)
+
+      - name: Check Go version
+        run: go version
